app = 'tiktok-ads-mcp'
primary_region = 'fra'  # Frankfurt - closest to Europe

[build]

[deploy]
  release_command = 'echo "Starting TikTok Ads MCP Server"'

[env]
  HOST = "0.0.0.0"
  PYTHON_VERSION = "3.11"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[experimental]
  auto_rollback = true