# fly.toml app configuration file generated for tiktok-ads-mcp on 2025-08-29T13:15:33Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tiktok-ads-mcp'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
